name: release
on:
  - push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: lint
        uses: hadolint/hadolint-action@v1.5.0
